config/routes.rb
Rails.application.routes.draw do
  get 'genre/index'
  get 'genre/new'
  get 'genre/create'
  get 'genre/show'
  get 'genre/edit'
  get 'genre/update'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'welcome#home'
  get 'welcome/about'
  get 'welcome/contact'
  get 'welcome/for_you'
  get 'welcome/trending'
  devise_for :users
  get 'profile' => 'users#show'
  resources :movies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_and_belongs_to_many :movies
end

app/models/movie.rb
class Movie < ApplicationRecord
	has_many :ratings
	has_many :users, :through => :ratings 
	has_and_belongs_to_many :genres
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :movie

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :ratings
  has_many :movies, :through => :ratings

  def full_name
  	"#{first_name} #{last_name}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!

	before_action :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
        	devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :age, :gender, :occupation, :zip])
        	devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :age, :gender, :occupation, :zip])
        end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show

	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
    @movies = Movie.all.limit(40)
    @recommended = Movie.last(10)
    @rated_by = current_user.ratings
  end

  def about
  end

  def contact
  end

  def for_you
  end

  def trending
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def gravatar_url(user)
		email_hash = Digest::MD5.hexdigest(user.email).downcase
		"http://gravatar.com/avatar/#{email_hash}/s=30"
	end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

 def average_ratings(movie)
  	avg_rating = 0
  	movie.ratings.each do |r|
  		avg_rating += r.rating
  	end
  	(movie.ratings.count != 0) ? (avg_rating / movie.ratings.count) : 0
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/genres/create.html.slim
h1 Genre#create
p Find me in app/views/genre/create.html.slim

app/views/genres/edit.html.slim
h1 Genre#edit
p Find me in app/views/genre/edit.html.slim

app/views/genres/index.html.slim
h1 Genre#index
p Find me in app/views/genre/index.html.slim

app/views/genres/new.html.slim
h1 Genre#new
p Find me in app/views/genre/new.html.slim

app/views/genres/show.html.slim
h1 Genre#show
p Find me in app/views/genre/show.html.slim

app/views/genres/update.html.slim
h1 Genre#update
p Find me in app/views/genre/update.html.slim

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= yield :title %> | CFiltering</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
  </head>

  <body>
    <%= render 'partials/navbar' %>
    <div class="container-fluid">
      <%= yield %>
    </div>
    <%= render 'partials/footer' %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>
  </body>
</html>

app/views/movies/create.html.slim
h1 Movies#create
p Find me in app/views/movies/create.html.slim

app/views/movies/destroy.html.slim
h1 Movies#destroy
p Find me in app/views/movies/destroy.html.slim

app/views/movies/edit.html.slim
h1 Movies#edit
p Find me in app/views/movies/edit.html.slim

app/views/movies/index.html.slim
h1 Movies#index
p Find me in app/views/movies/index.html.slim

app/views/movies/new.html.slim
h1 Movies#new
p Find me in app/views/movies/new.html.slim

app/views/movies/show.html.slim
.row
  .col-md-6
    = image_tag "/jumbo-image.jpg", class: "img-fluid"
  .col-md-6
    .h2.display-6
      = @movie.name
      hr
      - average_ratings(@movie).to_i.times do |icon|
        span class="fa fa-star gold-star"
      hr
      = link_to("Rate", root_path)
      hr
      h2.display-6 Your Information
      

app/views/movies/update.html.slim
h1 Movies#update
p Find me in app/views/movies/update.html.slim

app/views/partials/_footer.html.slim
/! Footer
footer.page-footer.font-small.unique-color-dark.mt-4
  div style=("background-color: #6351ce;") 
    .container
      /! Grid row
      .row.py-4.d-flex.align-items-center
        /! Grid column
        .col-md-6.col-lg-5.text-center.text-md-left.mb-4.mb-md-0
          h6.mb-0 style="color: #fff" Get connected with us on social networks!
        /! Grid column
        /! Grid column
        .col-md-6.col-lg-7.text-center.text-md-right
          /! Facebook
          a.fb-ic
            i.fa.fa-facebook.white-text.mr-4
          /! Twitter
          a.tw-ic
            i.fa.fa-twitter.white-text.mr-4
          /! Google +
          a.gplus-ic
            i.fa.fa-google-plus.white-text.mr-4
          /! Linkedin
          a.li-ic
            i.fa.fa-linkedin.white-text.mr-4
          /! Instagram
          a.ins-ic
            i.fa.fa-instagram.white-text
        /! Grid column
      /! Grid row
  /! Footer Links
  .container.text-center.text-md-left.mt-5
    /! Grid row
    .row.mt-3
      /! Grid column
      .col-md-3.col-lg-4.col-xl-3.mx-auto.mb-4
        /! Content
        h6.text-uppercase.font-weight-bold Company name
        hr.deep-purple.accent-2.mb-4.mt-0.d-inline-block.mx-auto style=("width: 60px;") /
        p Here you can use rows and columns here to organize your footer content. Lorem ipsum dolor sit amet, consectetur adipisicing elit.
      /! Grid column
      /! Grid column
      .col-md-2.col-lg-2.col-xl-2.mx-auto.mb-4
        /! Links
        h6.text-uppercase.font-weight-bold Products
        hr.deep-purple.accent-2.mb-4.mt-0.d-inline-block.mx-auto style=("width: 60px;") /
        p
          a href="#!"  MDBootstrap
        p
          a href="#!"  MDWordPress
        p
          a href="#!"  BrandFlow
        p
          a href="#!"  Bootstrap Angular
      /! Grid column
      /! Grid column
      .col-md-3.col-lg-2.col-xl-2.mx-auto.mb-4
        /! Links
        h6.text-uppercase.font-weight-bold Useful links
        hr.deep-purple.accent-2.mb-4.mt-0.d-inline-block.mx-auto style=("width: 60px;") /
        p
          a href="#!"  Your Account
        p
          a href="#!"  Become an Affiliate
        p
          a href="#!"  Shipping Rates
        p
          a href="#!"  Help
      /! Grid column
      /! Grid column
      .col-md-4.col-lg-3.col-xl-3.mx-auto.mb-md-0.mb-4
        /! Links
        h6.text-uppercase.font-weight-bold Contact
        hr.deep-purple.accent-2.mb-4.mt-0.d-inline-block.mx-auto style=("width: 60px;") /
        p
          i.fa.fa-home.mr-3
          | New York, NY 10012, US
        p
          i.fa.fa-envelope.mr-3
          | info@example.com
        p
          i.fa.fa-phone.mr-3
          | + 01 234 567 88
        p
          i.fa.fa-print.mr-3
          | + 01 234 567 89
      /! Grid column
    /! Grid row
  /! Footer Links
  /! Copyright
  .footer-copyright.text-center.py-3
    | © 2018 Copyright:
    a href="https://mdbootstrap.com/bootstrap-tutorial/"  Latent Collaborative Filtering
  /! Copyright
/! Footer

app/views/partials/_navbar.html.slim
nav.navbar.navbar-expand-lg.navbar-light style="background-color: #fff;"
  .container
    = link_to "LCFiltering", root_path, class: "navbar-brand"
    button.navbar-toggler aria-controls="navbarSupportedContent" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarSupportedContent" data-toggle="collapse" type="button" 
      span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      ul.navbar-nav.ml-auto
        li.nav-item.active
          a.nav-link href="/" 
            | &nbsp;HOME
            span.sr-only (current)
        li.nav-item.active
          = link_to "FOR YOU", root_path, class: "nav-link"
        li.nav-item.active
          = link_to "TRENDING", root_path, class: "nav-link"
        li.nav-item
          a.nav-link href="#"  DON'T MISS
        - if user_signed_in?
          li.nav-item.dropdown
            a#navbarDropdown.nav-link.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button" 
              = image_tag gravatar_url(current_user), class: "avatar-thumbnail rounded-circle navbar-item"
              span &nbsp;
              = current_user.full_name
            .dropdown-menu aria-labelledby="navbarDropdown" 
              = link_to "Profile", profile_path, class: "dropdown-item"
              = link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item"
              = link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item"
              a.dropdown-item href="#"  Another action
              .dropdown-divider
              a.dropdown-item href="#"  Something else here
      
    

app/views/users/show.html.slim
- content_for(:title) do
	p Profile



.row
  .col-md-4
	h2.display-6 Your Information


	.card
	  = image_tag gravatar_url(current_user), class: "card-img-top avatar-full"
	  .card-body
	    .card-title
	      .h6.display-6
	        = current_user.first_name
	        hr
	        = current_user.last_name
	        hr
	        = current_user.email
	        hr
	        = current_user.age
	        hr
	        = current_user.gender
	        hr
	        = current_user.occupation

app/views/welcome/about.html.slim
h1 Welcome#about
p Find me in app/views/welcome/about.html.slim

app/views/welcome/contact.html.slim
h1 Welcome#contact
p Find me in app/views/welcome/contact.html.slim

app/views/welcome/for_you.html.slim
h1 Welcome#for_you
p Find me in app/views/welcome/for_you.html.slim

app/views/welcome/home.html.slim
.jumbotron.jumbotorn-fluid style="background-image: url('jumbo-image.jpg');background-position: center;background-size: cover;"
  h2.display-4 Movie Reco System
  p.lead This project uses Latent collaborative filtering approach to recommend you the movies you are most likely to watch.
  hr.my-4
  p It uses utility classes for typography and spacing to space content out within the larger container.
  p.lead
    a.btn.btn-info.btn-lg.link-button href="#" role="button"  Learn more

.row
  .col-md-9
    h3.display-6 Latest Movies
    .row
      - @movies.each do |movie|
        .col-md-3
          .card.movies-card
            = image_tag "/jumbo-image.jpg", class: "card-img-top"
            .card-body
              .card-title
                = link_to movie.name, movie_path(movie)
              .card-text
                = movie.generes
                = link_to "Watch Now", root_path, class: "btn btn-info btn-sm card-link"
              .pull-right
                - average_ratings(movie).to_i.times do
                  i class="fa fa-star gold-star"

  .col-md-3
    h4.display-6 Recommended
    - @recommended.each do |rec|
      = link_to rec.name, movie_path(rec)
      br
    - @rated_by.each do |rat|
      = rat.user_id

app/views/welcome/trending.html.slim
h1 Welcome#trending
p Find me in app/views/welcome/trending.html.slim